import React from 'react';
import { FileText, Download, Activity, Users, BookOpen, CreditCard } from 'lucide-react';

const Reports = () => {
  const reportTypes = [
    { title: 'Academic Performance', icon: BookOpen, color: '#3B82F6', desc: 'Class-wise and student-wise grade distributions and trends.' },
    { title: 'Attendance Summary', icon: Activity, color: '#10B981', desc: 'Monthly attendance rates, chronic absenteeism, and late arrivals.' },
    { title: 'Fee Collection', icon: CreditCard, color: '#F59E0B', desc: 'Defaulters list, collection projections, and historical revenue.' },
    { title: 'Demographics & Enrollment', icon: Users, color: '#8B5CF6', desc: 'Student population breakdown by age, gender, and location.' },
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', width: '100%', height: '100%' }}>
      <div className="card">
        <div className="card-header">
          <div className="card-title">Generated Reports</div>
        </div>
        <p className="text-muted" style={{ marginBottom: '24px' }}>Select a report category below to configure and generate detailed analytics.</p>
        
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '24px' }}>
          {reportTypes.map((report, i) => (
            <div key={i} style={{ border: '1px solid var(--color-border)', borderRadius: '12px', padding: '24px', transition: 'all 0.2s', cursor: 'pointer' }} className="report-card hover-shadow">
              <div style={{ width: '48px', height: '48px', borderRadius: '12px', backgroundColor: report.color + '15', color: report.color, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '16px' }}>
                <report.icon size={24} />
              </div>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: '8px' }}>{report.title}</h3>
              <p className="text-muted" style={{ fontSize: '0.85rem', lineHeight: 1.5, marginBottom: '20px' }}>{report.desc}</p>
              <button className="btn-outline" style={{ width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', color: 'var(--color-text-main)' }}>
                <FileText size={16} /> Configure Report
              </button>
            </div>
          ))}
        </div>
      </div>
      
      <div className="card" style={{ flex: 1 }}>
        <div className="card-header">
          <div className="card-title">Recent Exports</div>
        </div>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th style={{ textAlign: 'left', padding: '12px', borderBottom: '1px solid var(--color-border)', color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>Report Name</th>
              <th style={{ textAlign: 'left', padding: '12px', borderBottom: '1px solid var(--color-border)', color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>Date Generated</th>
              <th style={{ textAlign: 'left', padding: '12px', borderBottom: '1px solid var(--color-border)', color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>Generated By</th>
              <th style={{ textAlign: 'right', padding: '12px', borderBottom: '1px solid var(--color-border)' }}></th>
            </tr>
          </thead>
          <tbody>
            {[
              { name: 'Term 1 Exam Results Summary.pdf', date: 'Aug 20, 2023 14:30', user: 'Admin User' },
              { name: 'Defaulters_List_Aug.csv', date: 'Aug 19, 2023 09:15', user: 'Accounts Dept' },
              { name: 'Staff_Attendance_July.xlsx', date: 'Aug 15, 2023 11:00', user: 'HR Dept' }
            ].map((exportItem, i) => (
              <tr key={i}>
                <td style={{ padding: '16px 12px', borderBottom: '1px solid var(--color-border)', fontWeight: 500 }}>{exportItem.name}</td>
                <td style={{ padding: '16px 12px', borderBottom: '1px solid var(--color-border)' }} className="text-muted">{exportItem.date}</td>
                <td style={{ padding: '16px 12px', borderBottom: '1px solid var(--color-border)' }} className="text-muted">{exportItem.user}</td>
                <td style={{ padding: '16px 12px', borderBottom: '1px solid var(--color-border)', textAlign: 'right' }}>
                  <button className="btn-outline" style={{ padding: '4px 12px', fontSize: '0.75rem', display: 'inline-flex', alignItems: 'center', gap: '4px' }}>
                    <Download size={12} /> Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      
      <style>{`
        .hover-shadow:hover {
          box-shadow: 0 4px 12px rgba(0,0,0,0.05);
          border-color: #d1d5db;
        }
      `}</style>
    </div>
  );
};

export default Reports;
